<a href="https://colab.research.google.com/github/jaramillooo/Proyecto_series_no_lineales/blob/main/proyecto12ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Daily Demand Forecasting Orders
 [Dataset link](https://archive.ics.uci.edu/dataset/409/daily+demand+forecasting+orders).


Variables:
- Week of the month	Feature	Integer	(first, second, third, fourth or fifth week)
- Day of the week	Feature	Integer	(Monday to Friday)
- Non-urgent order	Feature	Continuous
- Urgent order	Feature	Continuous
- Order type A	Feature	Continuous
- Order type B	Feature	Continuous
- Order type C	Feature	Continuous
- Fiscal sector orders	Feature	Continuous
- Orders from the traffic controller sector	Feature	Integer
- Banking orders (1)	Feature	Integer

The dataset was collected during 60 days, this is a real database of a brazilian logistics company. The dataset has twelve predictive attributes and a target that is the total of orders for daily treatment. The database was used in academic research at the Universidade Nove de Julho.
.arff header for Weka:

@relation Daily_Demand_Forecasting_Orders

@attribute Week_of_the_month {1.0, 2.0, 3.0, 4.0, 5.0}

@attribute Day_of_the_week_(Monday_to_Friday) {2.0, 3.0, 4.0, 5.0, 6.0}

@attribute Non_urgent_order integer

@attribute Urgent_order integer

@attribute Order_type_A integer

@attribute Order_type_B integer

@attribute Order_type_C integer

@attribute Fiscal_sector_orders integer

@attribute Orders_from_the_traffic_controller_sector integer

@attribute Banking_orders_(1) integer

@attribute Banking_orders_(2) integer

@attribute Banking_orders_(3) integer

@attribute Target_(Total_orders) integer

In [2]:
pip install ucimlrepo

Collecting ucimlrepo
  Downloading ucimlrepo-0.0.6-py3-none-any.whl (8.0 kB)
Installing collected packages: ucimlrepo
Successfully installed ucimlrepo-0.0.6

In [3]:
from ucimlrepo import fetch_ucirepo

# fetch dataset
daily_demand_forecasting_orders = fetch_ucirepo(id=409)

# data (as pandas dataframes)
X = daily_demand_forecasting_orders.data.features
y = daily_demand_forecasting_orders.data.targets

# metadata
print(daily_demand_forecasting_orders.metadata)

# variable information
print(daily_demand_forecasting_orders.variables)

{'uci_id': 409, 'name': 'Daily Demand Forecasting Orders', 'repository_url': 'https://archive.ics.uci.edu/dataset/409/daily+demand+forecasting+orders', 'data_url': 'https://archive.ics.uci.edu/static/public/409/data.csv', 'abstract': 'The dataset was collected during 60 days, this is a real database of a brazilian logistics company.', 'area': 'Business', 'tasks': ['Regression'], 'characteristics': ['Time-Series'], 'num_instances': 60, 'num_features': 12, 'feature_types': ['Integer'], 'demographics': [], 'target_col': ['Total orders'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 2016, 'last_updated': 'Thu Mar 21 2024', 'dataset_doi': '10.24432/C5BC8T', 'creators': ['Ricardo Ferreira', 'Andrea Martiniano', 'Arthur Ferreira', 'Aleister Ferreira', 'Renato Sassi'], 'intro_paper': {'title': 'Study on Daily Demand Forecasting Orders using Artificial Neural Network', 'authors': 'R. P. Ferreira, Andr√©a Martiniano, Arthur Arruda Leal Ferreira, Aleister Ferreira, R. Sassi', 'published_in': 'IEEE Latin America Transactions', 'year': 2016, 'url': 'https://www.semanticscholar.org/paper/Study-on-Daily-Demand-Forecasting-Orders-using-Ferreira-Martiniano/ada83243deefbfadfe55eb96880abb7b83cd043a', 'doi': None}, 'additional_info': {'summary': 'The database was collected during 60 days, this is a real database of a Brazilian company of large logistics. Twelve predictive attributes and a target that is the total of orders for daily. treatment', 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'The dataset was collected during 60 days, this is a real database of a brazilian logistics company. The dataset has twelve predictive attributes and a target that is the total of orders for daily treatment. The database was used in academic research at the Universidade Nove de Julho.\n.arff header for Weka:\n@relation Daily_Demand_Forecasting_Orders\n@attribute Week_of_the_month {1.0, 2.0, 3.0, 4.0, 5.0}\n@attribute Day_of_the_week_(Monday_to_Friday) {2.0, 3.0, 4.0, 5.0, 6.0}\n@attribute Non_urgent_order integer\n@attribute Urgent_order integer\n@attribute Order_type_A integer\n@attribute Order_type_B integer\n@attribute Order_type_C integer\n@attribute Fiscal_sector_orders integer\n@attribute Orders_from_the_traffic_controller_sector integer\n@attribute Banking_orders_(1) integer\n@attribute Banking_orders_(2) integer\n@attribute Banking_orders_(3) integer\n@attribute Target_(Total_orders) integer\n@data', 'citation': None}}
                                         name     role        type  \
0                           Week of the month  Feature     Integer
1                             Day of the week  Feature     Integer
2                            Non-urgent order  Feature  Continuous
3                                Urgent order  Feature  Continuous
4                                Order type A  Feature  Continuous
5                                Order type B  Feature  Continuous
6                                Order type C  Feature  Continuous
7                        Fiscal sector orders  Feature  Continuous
8   Orders from the traffic controller sector  Feature     Integer
9                          Banking orders (1)  Feature     Integer
10                         Banking orders (2)  Feature     Integer
11                         Banking orders (3)  Feature     Integer
12                               Total orders   Target  Continuous

   demographic                                   description units  \
0         None  (first, second, third, fourth or fifth week)  None
1         None                            (Monday to Friday)  None
2         None                                          None  None
3         None                                          None  None
4         None                                          None  None
5         None                                          None  None
6         None                                          None  None
7         None                                          None  None
8         None                                          None  None
9         None                                          None  None
10        None                                          None  None
11        None                                          None  None
12        None                                          None  None

   missing_values
0              no
1              no
2              no
3              no
4              no
5              no
6              no
7              no
8              no
9              no
10             no
11             no
12             no

In [4]:
X.head(10)

,Week of the month,Day of the week,Non-urgent order,Urgent order,Order type A,Order type B,Order type C,Fiscal sector orders,Orders from the traffic controller sector,Banking orders (1),Banking orders (2),Banking orders (3)
0,1,4,316.307,223.270,61.543,175.586,302.448,0.000,65556,44914,188411,14793
1,1,5,128.633,96.042,38.058,56.037,130.580,0.000,40419,21399,89461,7679
2,1,6,43.651,84.375,21.826,25.125,82.461,1.386,11992,3452,21305,14947
3,2,2,171.297,127.667,41.542,113.294,162.284,18.156,49971,33703,69054,18423
4,2,3,90.532,113.526,37.679,56.618,116.220,6.459,48534,19646,16411,20257
5,2,4,110.925,96.360,30.792,50.704,125.868,79.000,52042,8773,47522,24966
6,2,5,144.124,118.919,43.304,66.371,153.368,0.000,46573,33597,48269,20973
7,2,6,119.379,113.870,38.584,85.961,124.413,15.709,35033,26278,56665,18502
8,3,2,218.856,124.381,33.973,148.274,162.044,1.054,66612,19461,103376,10458
9,3,3,146.518,101.045,36.399,43.306,168.723,865.000,58224,7742,82395,11948

In [5]:
df = X.copy()
import pandas as pd
total_days = 60
df['date'] = pd.to_datetime('2024') + pd.to_timedelta(df['Week of the month'] * 7 + df['Day of the week'] - 1, unit='D')
df['date'] = df['date'].clip(lower=pd.to_datetime('2024'), upper=pd.to_datetime('2024') + pd.to_timedelta(total_days - 1, unit='D'))
df.set_index('date', inplace=True)

In [6]:
df.head(10)

,Week of the month,Day of the week,Non-urgent order,Urgent order,Order type A,Order type B,Order type C,Fiscal sector orders,Orders from the traffic controller sector,Banking orders (1),Banking orders (2),Banking orders (3)
date,,,,,,,,,,,,
2024-01-11,1,4,316.307,223.270,61.543,175.586,302.448,0.000,65556,44914,188411,14793
2024-01-12,1,5,128.633,96.042,38.058,56.037,130.580,0.000,40419,21399,89461,7679
2024-01-13,1,6,43.651,84.375,21.826,25.125,82.461,1.386,11992,3452,21305,14947
2024-01-16,2,2,171.297,127.667,41.542,113.294,162.284,18.156,49971,33703,69054,18423
2024-01-17,2,3,90.532,113.526,37.679,56.618,116.220,6.459,48534,19646,16411,20257
2024-01-18,2,4,110.925,96.360,30.792,50.704,125.868,79.000,52042,8773,47522,24966
2024-01-19,2,5,144.124,118.919,43.304,66.371,153.368,0.000,46573,33597,48269,20973
2024-01-20,2,6,119.379,113.870,38.584,85.961,124.413,15.709,35033,26278,56665,18502
2024-01-23,3,2,218.856,124.381,33.973,148.274,162.044,1.054,66612,19461,103376,10458
2024-01-24,3,3,146.518,101.045,36.399,43.306,168.723,865.000,58224,7742,82395,11948